genesis-file="/config/genesis.json"
data-path="/data/"
data-storage-format = "FOREST"

rpc-http-api = ["ETH", "NET", "QBFT", "TXPOOL", "WEB3", "TRACE"]
rpc-http-cors-origins = ["*"]
rpc-http-host = "0.0.0.0"
rpc-http-enabled = true
rpc-http-port = "8545"
# rpc-gas-cap= <BLOCK_GASLIMIT>
rpc-ws-enabled = true
rpc-ws-api = ["ETH", "NET", "QBFT", "TXPOOL", "WEB3", "TRACE"]

nat-method = "AUTO"
host-allowlist = ["*"]
engine-host-allowlist = ["*"]

bootnodes = [
    "enode://553afe137559c4fbf5d0c7646603539755a37cf60b71a1a1574845ba4a7c822a4e422f908c2487c9b6b00dc262aafba8daa45de60bda93ba92ca25524d857eb0@bbootnode1:30303",
    "enode://b905139541a41fe7e3d6a005b3fdbe606f2885b58d3179b9d96828c4bd57ab02c8c80a63066e4b6b942da9d256845b6455a933e64ca5c289420030eb64885db5@bbootnode2:30303",
]

tx-pool = "SEQUENCED"
tx-pool-no-local-priority = true

[experiment]
Xdns-enabled = true
Xdns-update-enabled = true
# Xplugin-rocksdb-max-open-files
# Xplugin-rocksdb-cache-capacity
# Xplugin-rocksdb-background-thread-count
# Xplugin-rocksdb-high-spec-enabled